## Importation des librairies

In [268]:
import pandas as pd
import numpy as np

## Lecture et traitement du DataSet

In [269]:
data = pd.read_csv("Recipe.csv", header=None)

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (27,28,29,30) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [270]:
data

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Canada,egg,yeast,wheat,milk,lard,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,pork,carrot,pea,onion,potato,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Canada,maple_syrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Canada,wheat,yeast,almond,honey,oat,date,vegetable_oil,whole_grain_wheat_flour,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,butter,lovage,clam,wheat,onion,thyme,potato,yeast,black_pepper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41820,Japan,wheat,mustard,onion,starch,parsley,cucumber,cream_cheese,chive,vegetable_oil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41821,Japan,pork,sesame_oil,nut,scallion,seaweed,chicken,egg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41822,Japan,vinegar,pepper,sake,corn,ginger,shallot,garlic,barley,soybean,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41823,Japan,vinegar,wheat,bacon,ginger,cabbage,egg,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41824,Japan,pepper,wheat,onion,soy_sauce,wasabi,sesame_seed,soybean,vegetable_oil,tuna,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [271]:
dodo = data.iloc[:, [0,1,2,3,4,5,6,7]]

In [272]:
dodo = dodo.dropna()

In [273]:
dodo = dodo.drop(0,axis=1)

In [274]:
ListeIndex = []
ListeGen = []
for i in dodo.index:
    for a in dodo.columns:
        ListeIndex+=[i]
        ListeGen+=[dodo[a][i]]

In [275]:
dodo = pd.DataFrame(data = {"Produit" : ListeGen, "NumTicket" : ListeIndex})

## Construction des règles d'association

In [277]:
#tableau croisé 0/1
DataFrame = pd.crosstab(dodo.NumTicket,dodo.Produit)

In [278]:
DataFrame

Produit,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,artichoke,asparagus,avocado,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
NumTicket,,,,,,,,,,,,,,,,,,,,,
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41815,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41820,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41821,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41822,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41824,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [279]:
#importation de la fonction apriori
from mlxtend.frequent_patterns import apriori
 
#itemsets frequents
freq_itemsets = apriori(DataFrame,min_support=0.025,max_len=3, use_colnames=True)

In [280]:
freq_itemsets.iloc[60:80, :]

     support                   itemsets
60  0.080842                    (yeast)
61  0.025249            (wheat, almond)
62  0.028117             (wheat, apple)
63  0.026117             (onion, bacon)
64  0.026985       (black_pepper, beef)
65  0.025060            (cayenne, beef)
66  0.082843              (beef, onion)
67  0.039515             (pepper, beef)
68  0.058650             (tomato, beef)
69  0.034269            (vinegar, beef)
70  0.042912     (black_pepper, butter)
71  0.032873    (black_pepper, cayenne)
72  0.042308     (black_pepper, garlic)
73  0.052234  (black_pepper, olive_oil)
74  0.108092      (black_pepper, onion)
75  0.051404     (black_pepper, tomato)
76  0.036081    (vinegar, black_pepper)
77  0.033514      (wheat, black_pepper)
78  0.095901    (cane_molasses, butter)
79  0.052649         (butter, cinnamon)